# Generated by Django 2.2.5 on 2020-05-06 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('resume_title', models.CharField(default='렛슨 제안서 제목을 입력해주세요', max_length=100)),
                ('instrument', models.CharField(choices=[('piano', '피아노'), ('violin', '바이올린'), ('cello', '첼로'), ('viola', '비올라'), ('double bass', '더블베이스'), ('harp', '하프'), ('flute', '플루트'), ('clarinet', '클라리넷'), ('oboe', '오보에'), ('basson', '바순'), ('trumpet', '트럼펫'), ('horn', '호른'), ('tuba', '튜바'), ('saxophone', '색소폰')], max_length=10)),
                ('final_degree', models.CharField(blank=True, choices=[('Associate degree', '전문학사'), ('Doctorl degree', '학사'), ("Master's degree", '석사'), ('Doctorl degree', '박사')], max_length=80, null=True)),
                ('college', models.CharField(blank=True, max_length=80, null=True)),
                ('is_graduated', models.BooleanField(default=False)),
                ('graduate_year', models.IntegerField(blank=True, choices=[(1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020, max_length=4, null=True, verbose_name='year')),
                ('awards', models.TextField(blank=True, null=True)),
                ('career', models.TextField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=80, null=True)),
                ('fee', models.IntegerField()),
                ('is_test_class_possible', models.BooleanField(default=False)),
                ('is_super_instructor', models.BooleanField(default=False)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
