# Generated by Django 2.2.5 on 2020-05-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='is_test_class_possible',
        ),
    ]
