# Generated by Django 2.2.5 on 2020-05-09 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_remove_resume_is_test_class_possible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='resumes.Resume'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resume',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='resumes.instrumentChoice'),
        ),
    ]
