# Generated by Django 2.2.5 on 2020-05-07 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='lesson_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
