# Generated by Django 2.2.5 on 2020-05-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200507_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
