# Generated by Django 2.2.5 on 2020-05-06 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='instrumentChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Instrument Choice',
            },
        ),
        migrations.CreateModel(
            name='LessonDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Lesson Day',
            },
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Lesson Type',
            },
        ),
        migrations.CreateModel(
            name='PreferStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Prefered Style',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('entrance exam', '입시'), ('hobby', '취미')], max_length=10)),
                ('current_skill', models.TextField()),
                ('skill_reference', models.FileField(blank=True, null=True, upload_to='')),
                ('goal', models.CharField(max_length=100)),
                ('lesson_count_per_week', models.CharField(blank=True, choices=[('1', '1주일 1회'), ('2', '1주일 2회'), ('3', '1주일 3회'), ('tbd', '추후 협의')], max_length=10, null=True)),
                ('desired_lesson_time', models.CharField(blank=True, choices=[('am.9 - pm.12', 'am.9 - pm.12'), ('pm.12 - pm.3', 'pm.12 - pm.3'), ('pm.3 - pm.6', 'pm.3 - pm.6'), ('pm.6 - pm.9', 'pm.6 - pm.9')], max_length=20, null=True)),
                ('desired_starting_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=80, null=True)),
                ('wanna_test_class', models.BooleanField(default=False)),
                ('desired_lesson_days', models.ManyToManyField(to='advertisements.LessonDay')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.instrumentChoice')),
                ('lesson_type', models.ManyToManyField(to='advertisements.LessonType')),
                ('prefer_style', models.ManyToManyField(to='advertisements.PreferStyle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
