# Generated by Django 2.2.5 on 2020-05-13 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_auto_20200509_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.CharField(choices=[('entrance exam', '입시'), ('hobby', '취미')], default='hobby', max_length=10),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='advertisements.instrumentChoice'),
        ),
    ]
