# Generated by Django 2.2.5 on 2020-05-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_auto_20200513_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.CharField(choices=[('hobby', '취미'), ('event', '각종 이벤트 및 경조사 연주'), ('exam', '입시'), ('competition', '콩쿠르')], max_length=10),
        ),
    ]
